---
nextcloud_enabled: false
nextcloud_available_externally: "true"

# directories
nextcloud_data_directory: "{{ docker_home }}/nextcloud"
nextcloud_user_directory: "{{ samba_shares_root }}/klaud/{{ nextcloud_username }}"

# network
nextcloud_port: "8080"
nextcloud_hostname: "nc"

# username / passwords
nextcloud_sql_user: "nextcloud-user"
nextcloud_sql_password: "nextcloud-pass"
nextcloud_sql_root_password: "nextcloud-secret"

# specs
nextcloud_memory: 1g
nextcloud_mysql_memory: 1g
nextcloud_upload: 10g
